# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/aston/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),aston)

$(call add-radio-file-sha1-checked,radio/abl.img,4fd35ac6a849b485ad89f34b20c82ad3349a82f7)
$(call add-radio-file-sha1-checked,radio/aop.img,7f878c33b4900e9027fc2e3fe441c56cc4214098)
$(call add-radio-file-sha1-checked,radio/aop_config.img,8abb30848f296bf3f0f3be4833e6ca1c8c9c4fd5)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,8f63273be5689721c76a428e25a5d320f821acc6)
$(call add-radio-file-sha1-checked,radio/cpucp.img,6344b15335ceb628f69d60b5b432c903addcb6b5)
$(call add-radio-file-sha1-checked,radio/devcfg.img,cac0eba6e481695278b1b5f535a2909d475b7a2e)
$(call add-radio-file-sha1-checked,radio/dsp.img,0cc5776825200ff66abc8606a52634c77b10e63d)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,230de1117ec4445208664b396f8bfab865c6bdbb)
$(call add-radio-file-sha1-checked,radio/hyp.img,7dfed558529c10751b18f721fa0bd936196f7802)
$(call add-radio-file-sha1-checked,radio/imagefv.img,8d5464ee735e298d28007a5a01ef18406240ab43)
$(call add-radio-file-sha1-checked,radio/keymaster.img,8c50e99b09144b93bd7995d3e451ff98896c0e8a)
$(call add-radio-file-sha1-checked,radio/modem.img,d39867d387cfb1a9ff1eb6616a0afccdf1d88ea7)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,1c584c7b98f32a7ccceebbad7564e3bc0944ccb0)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,efc097912a897e3fae4dbb9225ab958207251481)
$(call add-radio-file-sha1-checked,radio/qupfw.img,e89db11d76a27837e23b75024d7d0f27f4aeccc8)
$(call add-radio-file-sha1-checked,radio/shrm.img,bb330ae54d3fb5ff398d028304fb427a4ca0e3af)
$(call add-radio-file-sha1-checked,radio/splash.img,0e82d9c1514da572cd55af48928475681fc15797)
$(call add-radio-file-sha1-checked,radio/tz.img,dd761c851772c715f79c1935cc5d80aefde09121)
$(call add-radio-file-sha1-checked,radio/uefi.img,09073a56b4cadc7dee43d23570c0516a173c7677)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,b043b2319783f54f0a2c9b9c37456756e904c4aa)
$(call add-radio-file-sha1-checked,radio/xbl.img,cd079abf5a1a51a292cc41920aa34f892b2160c8)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,676f973778c085e14b975851126588c166ee674c)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,55b36bf41ba39f3e63905e0c562efd79805f2417)

endif
